import { WordHuntProgress } from '../types/wordHunt';
import { LearningActivity, LearningMode } from '../types/story';

const vocabularyMode: LearningMode = {
  id: 1,
  name: 'Vocabulary Learning',
  description: 'Luyen tap va ghi nho tu vung qua cac hoat dong game hoa.',
};

const wordHuntActivity: LearningActivity = {
  id: 31,
  title: 'Word Hunt',
  description: 'Tim tu vung theo chu de trong bang chu cai.',
  type: 4,
  learningMode: vocabularyMode,
};

export const mockWordHuntProgress: WordHuntProgress[] = [
  {
    id: 301,
    isCompleted: true,
    progressPercent: 100,
    score: 5,
    createdAt: '2026-03-28T08:00:00',
    completedAt: '2026-03-28T08:10:00',
    hintsUsedToday: 0,
    learningLesson: {
      id: 31,
      title: 'Animals',
      type: 'WORD_HUNT',
      description: 'Tim 5 tu vung chu de dong vat trong 01:45.',
      learningActivity: wordHuntActivity,
      image: { url: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=640' },
      content: {
        categoryKey: 'animals',
        categoryLabel: 'Animals',
        boardSize: 6,
        timeLimitSeconds: 105,
        targetWordCount: 5,
        maxHintsPerDay: 3,
        difficulty: 'EASY',
        icon: 'paw',
        cardColor: '#DDF5E5',
        iconColor: '#16A34A',
        objectiveText: 'Muc tieu: 5 tu',
        words: [
          { word: 'LION', meaningVi: 'Su tu' },
          { word: 'TIGER', meaningVi: 'Ho' },
          { word: 'RABBIT', meaningVi: 'Tho' },
          { word: 'HORSE', meaningVi: 'Ngua' },
          { word: 'SNAKE', meaningVi: 'Ran' },
          { word: 'MONKEY', meaningVi: 'Khi' },
        ],
      },
    },
  },
  {
    id: 302,
    isCompleted: true,
    progressPercent: 100,
    score: 5,
    createdAt: '2026-03-28T09:00:00',
    completedAt: '2026-03-28T09:12:00',
    hintsUsedToday: 1,
    learningLesson: {
      id: 32,
      title: 'Nature',
      type: 'WORD_HUNT',
      description: 'Tap trung nhin nhanh, tim du 5 tu trong chu de thien nhien.',
      learningActivity: wordHuntActivity,
      image: { url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=640' },
      content: {
        categoryKey: 'nature',
        categoryLabel: 'Nature',
        boardSize: 8,
        timeLimitSeconds: 105,
        targetWordCount: 5,
        maxHintsPerDay: 3,
        difficulty: 'EASY',
        icon: 'leaf',
        cardColor: '#DCFCE7',
        iconColor: '#16A34A',
        objectiveText: 'Muc tieu: 5 tu',
        words: [
          { word: 'RIVER', meaningVi: 'Song' },
          { word: 'MOUNTAIN', meaningVi: 'Nui' },
          { word: 'FOREST', meaningVi: 'Rung' },
          { word: 'RAIN', meaningVi: 'Mua' },
          { word: 'CLOUD', meaningVi: 'May' },
          { word: 'STONE', meaningVi: 'Da' },
        ],
      },
    },
  },
  {
    id: 303,
    isCompleted: false,
    progressPercent: 40,
    score: 4,
    createdAt: '2026-03-29T07:30:00',
    hintsUsedToday: 0,
    learningLesson: {
      id: 33,
      title: 'Food',
      type: 'WORD_HUNT',
      description: 'Man dang choi: tim du 5 tu truoc khi het gio.',
      learningActivity: wordHuntActivity,
      image: { url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=640' },
      content: {
        categoryKey: 'food',
        categoryLabel: 'Food',
        boardSize: 10,
        timeLimitSeconds: 105,
        targetWordCount: 5,
        maxHintsPerDay: 3,
        difficulty: 'MEDIUM',
        icon: 'silverware-fork-knife',
        cardColor: '#FDE9D2',
        iconColor: '#F97316',
        objectiveText: 'Muc tieu: 5 tu',
        words: [
          { word: 'PIZZA', meaningVi: 'Pizza' },
          { word: 'CAKE', meaningVi: 'Banh kem' },
          { word: 'SOUP', meaningVi: 'Sup' },
          { word: 'TACO', meaningVi: 'Banh taco' },
          { word: 'RICE', meaningVi: 'Gao' },
          { word: 'STEAK', meaningVi: 'Bittet' },
          { word: 'BURGER', meaningVi: 'Hamburger' },
        ],
      },
    },
  },
  {
    id: 304,
    isCompleted: false,
    progressPercent: 0,
    createdAt: '2026-03-29T08:00:00',
    hintsUsedToday: 0,
    learningLesson: {
      id: 34,
      title: 'Travel',
      type: 'WORD_HUNT',
      description: 'Mo khoa sau khi hoan thanh Food.',
      learningActivity: wordHuntActivity,
      image: { url: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=640' },
      content: {
        categoryKey: 'travel',
        categoryLabel: 'Travel',
        boardSize: 8,
        timeLimitSeconds: 120,
        targetWordCount: 6,
        maxHintsPerDay: 3,
        difficulty: 'MEDIUM',
        icon: 'airplane',
        cardColor: '#E5E7EB',
        iconColor: '#94A3B8',
        objectiveText: 'Muc tieu: 6 tu',
        unlockRequirementText: 'Can vuot qua Food de mo khoa',
        words: [
          { word: 'HOTEL', meaningVi: 'Khach san' },
          { word: 'FLIGHT', meaningVi: 'Chuyen bay' },
          { word: 'PASSPORT', meaningVi: 'Ho chieu' },
          { word: 'TICKET', meaningVi: 'Ve' },
          { word: 'LUGGAGE', meaningVi: 'Hanh ly' },
          { word: 'BEACH', meaningVi: 'Bai bien' },
        ],
      },
    },
  },
  {
    id: 305,
    isCompleted: false,
    progressPercent: 0,
    createdAt: '2026-03-29T08:30:00',
    hintsUsedToday: 0,
    learningLesson: {
      id: 35,
      title: 'Sports',
      type: 'WORD_HUNT',
      description: 'Mo khoa sau khi hoan thanh Travel.',
      learningActivity: wordHuntActivity,
      image: { url: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=640' },
      content: {
        categoryKey: 'sports',
        categoryLabel: 'Sports',
        boardSize: 10,
        timeLimitSeconds: 120,
        targetWordCount: 6,
        maxHintsPerDay: 3,
        difficulty: 'HARD',
        icon: 'basketball',
        cardColor: '#E5E7EB',
        iconColor: '#94A3B8',
        objectiveText: 'Muc tieu: 6 tu',
        unlockRequirementText: 'Can vuot qua Travel de mo khoa',
        words: [
          { word: 'TENNIS', meaningVi: 'Quan vot' },
          { word: 'SOCCER', meaningVi: 'Bong da' },
          { word: 'BOXING', meaningVi: 'Quyen anh' },
          { word: 'RUNNING', meaningVi: 'Chay bo' },
          { word: 'SWIM', meaningVi: 'Boi loi' },
          { word: 'VOLLEY', meaningVi: 'Bong chuyen' },
        ],
      },
    },
  },
  {
    id: 306,
    isCompleted: false,
    progressPercent: 0,
    createdAt: '2026-03-29T09:00:00',
    hintsUsedToday: 0,
    learningLesson: {
      id: 36,
      title: 'Technology',
      type: 'WORD_HUNT',
      description: 'Mo khoa sau khi hoan thanh Sports.',
      learningActivity: wordHuntActivity,
      image: { url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=640' },
      content: {
        categoryKey: 'technology',
        categoryLabel: 'Technology',
        boardSize: 10,
        timeLimitSeconds: 150,
        targetWordCount: 7,
        maxHintsPerDay: 3,
        difficulty: 'HARD',
        icon: 'cpu-64-bit',
        cardColor: '#E5E7EB',
        iconColor: '#94A3B8',
        objectiveText: 'Muc tieu: 7 tu',
        unlockRequirementText: 'Can vuot qua Sports de mo khoa',
        words: [
          { word: 'SERVER', meaningVi: 'May chu' },
          { word: 'ROUTER', meaningVi: 'Bo dinh tuyen' },
          { word: 'CODING', meaningVi: 'Lap trinh' },
          { word: 'BINARY', meaningVi: 'Nhi phan' },
          { word: 'MOBILE', meaningVi: 'Di dong' },
          { word: 'CLOUD', meaningVi: 'Dam may' },
          { word: 'SCREEN', meaningVi: 'Man hinh' },
        ],
      },
    },
  },
];
